/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedResumeNewRouteImport } from './routes/_authenticated/resume.new'
import { Route as AuthenticatedResumeIdEditRouteImport } from './routes/_authenticated/resume.$id.edit'
import { Route as AuthenticatedResumeIdExportRouteImport } from './routes/_authenticated/resume.$id.export'
import { Route as AuthenticatedResumeIdOptimizeRouteImport } from './routes/_authenticated/resume.$id.optimize'
import { Route as AuthenticatedResumeIdUploadRouteImport } from './routes/_authenticated/resume.$id.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeNewRoute = AuthenticatedResumeNewRouteImport.update({
  id: '/resume/new',
  path: '/resume/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeIdEditRoute =
  AuthenticatedResumeIdEditRouteImport.update({
    id: '/resume/$id/edit',
    path: '/resume/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeIdExportRoute =
  AuthenticatedResumeIdExportRouteImport.update({
    id: '/resume/$id/export',
    path: '/resume/$id/export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeIdOptimizeRoute =
  AuthenticatedResumeIdOptimizeRouteImport.update({
    id: '/resume/$id/optimize',
    path: '/resume/$id/optimize',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeIdUploadRoute =
  AuthenticatedResumeIdUploadRouteImport.update({
    id: '/resume/$id/upload',
    path: '/resume/$id/upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/resume/new': typeof AuthenticatedResumeNewRoute
  '/resume/$id/edit': typeof AuthenticatedResumeIdEditRoute
  '/resume/$id/export': typeof AuthenticatedResumeIdExportRoute
  '/resume/$id/optimize': typeof AuthenticatedResumeIdOptimizeRoute
  '/resume/$id/upload': typeof AuthenticatedResumeIdUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/resume/new': typeof AuthenticatedResumeNewRoute
  '/resume/$id/edit': typeof AuthenticatedResumeIdEditRoute
  '/resume/$id/export': typeof AuthenticatedResumeIdExportRoute
  '/resume/$id/optimize': typeof AuthenticatedResumeIdOptimizeRoute
  '/resume/$id/upload': typeof AuthenticatedResumeIdUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/resume/new': typeof AuthenticatedResumeNewRoute
  '/_authenticated/resume/$id/edit': typeof AuthenticatedResumeIdEditRoute
  '/_authenticated/resume/$id/export': typeof AuthenticatedResumeIdExportRoute
  '/_authenticated/resume/$id/optimize': typeof AuthenticatedResumeIdOptimizeRoute
  '/_authenticated/resume/$id/upload': typeof AuthenticatedResumeIdUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/resume/new'
    | '/resume/$id/edit'
    | '/resume/$id/export'
    | '/resume/$id/optimize'
    | '/resume/$id/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/resume/new'
    | '/resume/$id/edit'
    | '/resume/$id/export'
    | '/resume/$id/optimize'
    | '/resume/$id/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/resume/new'
    | '/_authenticated/resume/$id/edit'
    | '/_authenticated/resume/$id/export'
    | '/_authenticated/resume/$id/optimize'
    | '/_authenticated/resume/$id/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume/new': {
      id: '/_authenticated/resume/new'
      path: '/resume/new'
      fullPath: '/resume/new'
      preLoaderRoute: typeof AuthenticatedResumeNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume/$id/edit': {
      id: '/_authenticated/resume/$id/edit'
      path: '/resume/$id/edit'
      fullPath: '/resume/$id/edit'
      preLoaderRoute: typeof AuthenticatedResumeIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume/$id/export': {
      id: '/_authenticated/resume/$id/export'
      path: '/resume/$id/export'
      fullPath: '/resume/$id/export'
      preLoaderRoute: typeof AuthenticatedResumeIdExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume/$id/optimize': {
      id: '/_authenticated/resume/$id/optimize'
      path: '/resume/$id/optimize'
      fullPath: '/resume/$id/optimize'
      preLoaderRoute: typeof AuthenticatedResumeIdOptimizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume/$id/upload': {
      id: '/_authenticated/resume/$id/upload'
      path: '/resume/$id/upload'
      fullPath: '/resume/$id/upload'
      preLoaderRoute: typeof AuthenticatedResumeIdUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedResumeNewRoute: typeof AuthenticatedResumeNewRoute
  AuthenticatedResumeIdEditRoute: typeof AuthenticatedResumeIdEditRoute
  AuthenticatedResumeIdExportRoute: typeof AuthenticatedResumeIdExportRoute
  AuthenticatedResumeIdOptimizeRoute: typeof AuthenticatedResumeIdOptimizeRoute
  AuthenticatedResumeIdUploadRoute: typeof AuthenticatedResumeIdUploadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedResumeNewRoute: AuthenticatedResumeNewRoute,
  AuthenticatedResumeIdEditRoute: AuthenticatedResumeIdEditRoute,
  AuthenticatedResumeIdExportRoute: AuthenticatedResumeIdExportRoute,
  AuthenticatedResumeIdOptimizeRoute: AuthenticatedResumeIdOptimizeRoute,
  AuthenticatedResumeIdUploadRoute: AuthenticatedResumeIdUploadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
